## 1. Import Data ##

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/data_science_job_posts_2025.csv")

print(df.shape)
df.head()

(944, 13)

,job_title,seniority_level,status,company,location,post_date,headquarter,industry,ownership,company_size,revenue,salary,skills
0,data scientist,senior,hybrid,company_003,"Grapevine, TX . Hybrid",17 days ago,"Bentonville, AR, US",Retail,Public,€352.44B,Public,"€100,472 - €200,938","['spark', 'r', 'python', 'scala', 'machine lea..."
1,data scientist,lead,hybrid,company_005,"Fort Worth, TX . Hybrid",15 days ago,"Detroit, MI, US",Manufacturing,Public,"155,030",€51.10B,"€118,733","['spark', 'r', 'python', 'sql', 'machine learn..."
2,data scientist,senior,on-site,company_007,"Austin, TX . Toronto, Ontario, Canada . Kirkla...",a month ago,"Redwood City, CA, US",Technology,Public,"25,930",€33.80B,"€94,987 - €159,559","['aws', 'git', 'python', 'docker', 'sql', 'mac..."
3,data scientist,senior,hybrid,company_008,"Chicago, IL . Scottsdale, AZ . Austin, TX . Hy...",8 days ago,"San Jose, CA, US",Technology,Public,"34,690",€81.71B,"€112,797 - €194,402","['sql', 'r', 'python']"
4,data scientist,NaN,on-site,company_009,On-site,3 days ago,"Stamford, CT, US",Finance,Private,"1,800",Private,"€114,172 - €228,337",[]

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 944 entries, 0 to 943
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_title        941 non-null    str
 1   seniority_level  884 non-null    str
 2   status           688 non-null    str
 3   company          944 non-null    str
 4   location         942 non-null    str
 5   post_date        944 non-null    str
 6   headquarter      944 non-null    str
 7   industry         944 non-null    str
 8   ownership        897 non-null    str
 9   company_size     944 non-null    str
 10  revenue          929 non-null    str
 11  salary           944 non-null    str
 12  skills           944 non-null    str
dtypes: str(13)
memory usage: 96.0 KB

In [3]:
df.isnull().sum()

job_title            3
seniority_level     60
status             256
company              0
location             2
post_date            0
headquarter          0
industry             0
ownership           47
company_size         0
revenue             15
salary               0
skills               0
dtype: int64

## 2. Remove Duplicates ##

In [4]:
df = df.drop_duplicates()

print(df.shape)

(944, 13)

## 3. Fill Missing Values ##

In [5]:
df["job_title"] = df["job_title"].fillna("Unknown")

df["seniority_level"] = df["seniority_level"].fillna("Unknown")

df["status"] = df["status"].fillna("Unknown")

df["ownership"] = df["ownership"].fillna("Unknown")

df["revenue"] = df["revenue"].fillna("Unknown")

df["location"] = df["location"].fillna("Unknown")

## 4. Convert Dates ##

In [6]:
df["post_date"] = pd.to_datetime(
    df["post_date"],
    errors="coerce"
)

/var/folders/b1/wmyxyb614r97qjky96lyz22r0000gn/T/ipykernel_94649/3847960083.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["post_date"] = pd.to_datetime(

## 5. Convert Salary to Numeric Average ##

In [7]:
import re

def salary_to_number(value):

    value = str(value)

    nums = re.findall(
        r"\d[\d,]*",
        value
    )

    nums = [
        int(x.replace(",", ""))
        for x in nums
    ]

    if len(nums) == 0:
        return np.nan

    if len(nums) == 1:
        return nums[0]

    return sum(nums)/len(nums)

df["salary_numeric"] = (
    df["salary"]
    .apply(salary_to_number)
)

## 6. Check Results ##

In [8]:
df[
    ["salary",
     "salary_numeric"]
].head()

                salary  salary_numeric
0  €100,472 - €200,938        150705.0
1             €118,733        118733.0
2   €94,987 - €159,559        127273.0
3  €112,797 - €194,402        153599.5
4  €114,172 - €228,337        171254.5

## 7. Save Results ##

In [9]:
df.to_csv(
    "../data/processed/cleaned_jobs.csv",
    index=False
)